version: 2
updates:
  # Check for updates to npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "javascript"
      - "automated pr"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"

  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
