---
#------------------------------------------------------------------------------
# - Run manage.py unit tests via Docker
# - Build from Dockerfile
# - Deploy to Kubernetes
#------------------------------------------------------------------------------
name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: [alpha, beta, next, main]
    paths:
      - "**.py"
      - "**.js"
      - "**.jsx"
      - "smarter/smarter/static/**"
      - "smarter/smarter/templates/**"
  pull_request_target:
    types: [closed]
    branches: [alpha, beta, next, main]
    paths:
      - "**.py"
      - "**.js"
      - "**.jsx"
      - "smarter/smarter/static/**"
      - "smarter/smarter/templates/**"

env:
  AWS_REGION: us-east-2
  ROOT_DOMAIN: "smarter.sh"

jobs:
  check_merged:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - id: check
        run: |
          echo "::set-output name=merged::false"
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "::set-output name=merged::true"
          fi

      - name: Check branch name
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/alpha" && "${{ github.ref }}" != "refs/heads/beta" && "${{ github.ref }}" != "refs/heads/next" && "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "This workflow can only run on alpha, beta, next, or main branches"
            exit 1
          fi

  test:
    needs: check_merged
    if: ${{ needs.check_merged.outputs.merged == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Set environment variable
        id: setenv
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/alpha" ]]; then
            echo "ENVIRONMENT=alpha" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/beta" ]]; then
            echo "ENVIRONMENT=beta" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/next" ]]; then
            echo "ENVIRONMENT=next" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          fi

      - name: Test
        uses: ./.github/actions/test
        with:
          environment: ${{ env.ENVIRONMENT }}
          root-domain: "${{ env.ROOT_DOMAIN }}"
          google-maps-api-key: "${{ secrets.GOOGLE_MAPS_API_KEY }}"
          openai-api-key: "${{ secrets.OPENAI_API_KEY }}"
          pinecone-api-key: "${{ secrets.PINECONE_API_KEY }}"
          pinecone-environment: "${{ secrets.PINECONE_ENVIRONMENT }}"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Set environment variable
        id: setenv
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/alpha" ]]; then
            echo "ENVIRONMENT=alpha" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/beta" ]]; then
            echo "ENVIRONMENT=beta" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/next" ]]; then
            echo "ENVIRONMENT=next" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          fi

      - name: Build
        uses: ./.github/actions/build
        with:
          environment: ${{ env.ENVIRONMENT }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      - name: Set environment variable
        id: setenv
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/alpha" ]]; then
            echo "ENVIRONMENT=alpha" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/beta" ]]; then
            echo "ENVIRONMENT=beta" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/next" ]]; then
            echo "ENVIRONMENT=next" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          fi

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: ${{ env.ENVIRONMENT }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          pinecone-api-key: ${{ secrets.PINECONE_API_KEY }}
          pinecone-environment: ${{ secrets.PINECONE_ENVIRONMENT }}
          google-maps-api-key: ${{ secrets.GOOGLE_MAPS_API_KEY }}
