---
#------------------------------------------------------------------------------
# - Build from Dockerfile
# - Run manage.py unit tests
#------------------------------------------------------------------------------
name: Deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  ROOT_DOMAIN: "smarter.sh"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      - name: Set environment variable
        id: setenv
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/alpha" ]]; then
            echo "ENVIRONMENT=alpha" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/beta" ]]; then
            echo "ENVIRONMENT=beta" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/next" ]]; then
            echo "ENVIRONMENT=next" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          else
            echo "This workflow can only run on alpha, beta, next, or main branches"
            exit 1
          fi

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: ${{ env.ENVIRONMENT }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          google-maps-api-key: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          llama-api-key: ${{ secrets.LLAMA_API_KEY }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          pinecone-api-key: ${{ secrets.PINECONE_API_KEY }}
          pinecone-environment: ${{ secrets.PINECONE_ENVIRONMENT }}
          social-auth-google-oauth2-key: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }}
          social-auth-google-oauth2-secret: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }}
          social-auth-github-key: ${{ secrets.SOCIAL_AUTH_GITHUB_KEY }}
          social-auth-github-secret: ${{ secrets.SOCIAL_AUTH_GITHUB_SECRET }}
          social-auth-linkedin-oauth2-key: ${{ secrets.SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY }}
          social-auth-linkedin-oauth2-secret: ${{ secrets.SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET }}
          mailchimp-api-key: ${{ secrets.MAILCHIMP_API_KEY }}
          mailchimp-list-id: ${{ secrets.MAILCHIMP_LIST_ID }}

      - name: Send Email
        uses: ./.github/actions/send-mail
        with:
          environment: ${{ env.ENVIRONMENT }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          subject: "GHA - Deployed ${{ env.ENVIRONMENT }}.platform.smarter.sh"
          body: "${{ env.ENVIRONMENT }}.platform.smarter.sh was deployed successfully."
