name: Release
on:
  push:
    branches:
      - main
  pull_request_target:
    types: [closed]
    branches: [main]

jobs:
  check_merged:
    runs-on: ubuntu-latest
    outputs:
      merged: ${{ steps.check.outputs.merged }}
    steps:
      - id: check
        run: |
          echo "::set-output name=merged::false"
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "::set-output name=merged::true"
          fi

  release:
    needs: check_merged
    if: ${{ needs.check_merged.outputs.merged == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - run: npm install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
