---
#---------------------------------------------------------
# - Create a semantical release
# - Merge main into next, alpha, beta, and next-major
#---------------------------------------------------------
name: Semantic Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  merge-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.PAT }}

  semantic-release:
    needs: merge-main
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}

    steps:
      - uses: actions/checkout@v4
        id: checkout
        with:
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          branches: |
            [
              'main'
            ]
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog # Ensure only these plugins are used
        env:
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
